[project]
name = "Helen_Test"
authors = [{name = "Helen", email = "helen@helen.org"}]
dynamic = ["version", "description"]

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"